# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContentWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets


class Ui_ContentWidget(object):
    def setupUi(self, ContentWidget):
        ContentWidget.setObjectName("ContentWidget")
        ContentWidget.resize(831, 615)
        self.verticalLayoutWidget = QtWidgets.QWidget(ContentWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 19, 811, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.subjectLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.subjectLabel.setObjectName("subjectLabel")
        self.horizontalLayout_2.addWidget(self.subjectLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.horizontalLayout_2.addWidget(self.subjectLineEdit)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fromLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fromLabel.setObjectName("fromLabel")
        self.horizontalLayout.addWidget(self.fromLabel)
        self.fromLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fromLineEdit.setObjectName("fromLineEdit")
        self.horizontalLayout.addWidget(self.fromLineEdit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.contentWebEngineView = QtWebEngineWidgets.QWebEngineView(self.verticalLayoutWidget)
        self.contentWebEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.contentWebEngineView.setObjectName("contentWebEngineView")
        self.verticalLayout.addWidget(self.contentWebEngineView)
        self.attachmentListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.attachmentListWidget.setObjectName("attachmentListWidget")
        self.verticalLayout.addWidget(self.attachmentListWidget)
        self.verticalLayout.setStretch(2, 8)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(ContentWidget)
        QtCore.QMetaObject.connectSlotsByName(ContentWidget)

    def retranslateUi(self, ContentWidget):
        _translate = QtCore.QCoreApplication.translate
        ContentWidget.setWindowTitle(_translate("ContentWidget", "Form"))
        self.subjectLabel.setText(_translate("ContentWidget", "Subject"))
        self.fromLabel.setText(_translate("ContentWidget", "From:"))

