# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateMessageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateMessageWidget(object):
    def setupUi(self, CreateMessageWidget):
        CreateMessageWidget.setObjectName("CreateMessageWidget")
        CreateMessageWidget.resize(823, 603)
        CreateMessageWidget.setBaseSize(QtCore.QSize(823, 603))
        self.verticalLayoutWidget = QtWidgets.QWidget(CreateMessageWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 19, 811, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.toLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toLabel.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.toLabel.setObjectName("toLabel")
        self.horizontalLayout_2.addWidget(self.toLabel)
        self.toLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.toLineEdit.setObjectName("toLineEdit")
        self.horizontalLayout_2.addWidget(self.toLineEdit)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.sendButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 9)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.subjectLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.subjectLabel.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.subjectLabel.setObjectName("subjectLabel")
        self.horizontalLayout.addWidget(self.subjectLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.horizontalLayout.addWidget(self.subjectLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.addAttachmentButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addAttachmentButton.setObjectName("addAttachmentButton")
        self.horizontalLayout.addWidget(self.addAttachmentButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.messageBoxTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.messageBoxTextEdit.setObjectName("messageBoxTextEdit")
        self.verticalLayout.addWidget(self.messageBoxTextEdit)
        self.attachmentListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.attachmentListWidget.setObjectName("attachmentListWidget")
        self.verticalLayout.addWidget(self.attachmentListWidget)
        self.verticalLayout.setStretch(2, 9)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(CreateMessageWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateMessageWidget)

    def retranslateUi(self, CreateMessageWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateMessageWidget.setWindowTitle(
            _translate("CreateMessageWidget", "Create Message")
        )
        self.toLabel.setText(_translate("CreateMessageWidget", "To:"))
        self.sendButton.setText(_translate("CreateMessageWidget", "Send"))
        self.subjectLabel.setText(_translate("CreateMessageWidget", "Subject:"))
        self.addAttachmentButton.setText(_translate("CreateMessageWidget", "Add"))
