from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThunderNOTBird(object):
    def setupUi(self, ThunderNOTBird):
        ThunderNOTBird.setObjectName("ThunderNOTBird")
        ThunderNOTBird.resize(807, 600)
        self.centralwidget = QtWidgets.QWidget(ThunderNOTBird)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 781, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.centralWidgetHorizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget
        )
        self.centralWidgetHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.centralWidgetHorizontalLayout.setObjectName(
            "centralWidgetHorizontalLayout"
        )
        self.foldersListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.foldersListWidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.foldersListWidget.setObjectName("foldersListWidget")
        item = QtWidgets.QListWidgetItem()
        self.foldersListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.foldersListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.foldersListWidget.addItem(item)
        self.centralWidgetHorizontalLayout.addWidget(self.foldersListWidget)
        self.mailTableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.mailTableWidget.setLocale(
            QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland)
        )
        self.mailTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mailTableWidget.setColumnCount(3)
        self.mailTableWidget.setObjectName("mailTableWidget")
        self.mailTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.mailTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.mailTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.mailTableWidget.setHorizontalHeaderItem(2, item)
        self.mailTableWidget.horizontalHeader().setVisible(True)
        self.mailTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.mailTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.mailTableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.mailTableWidget.verticalHeader().setVisible(False)
        self.mailTableWidget.verticalHeader().setDefaultSectionSize(100)
        self.centralWidgetHorizontalLayout.addWidget(self.mailTableWidget)
        self.centralWidgetHorizontalLayout.setStretch(0, 1)
        self.centralWidgetHorizontalLayout.setStretch(1, 4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 781, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.toolbarVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.toolbarVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.toolbarVerticalLayout.setObjectName("toolbarVerticalLayout")
        self.createMessageToolButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.createMessageToolButton.setFont(font)
        self.createMessageToolButton.setObjectName("createMessageToolButton")
        self.toolbarVerticalLayout.addWidget(self.createMessageToolButton)
        self.toolbarVerticalLayout.setStretch(0, 3)
        ThunderNOTBird.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ThunderNOTBird)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        ThunderNOTBird.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ThunderNOTBird)
        self.statusbar.setObjectName("statusbar")
        ThunderNOTBird.setStatusBar(self.statusbar)
        self.actionCreate_a_new_message = QtWidgets.QAction(ThunderNOTBird)
        self.actionCreate_a_new_message.setObjectName("actionCreate_a_new_message")
        self.actionDelete_message = QtWidgets.QAction(ThunderNOTBird)
        self.actionDelete_message.setObjectName("actionDelete_message")
        self.actionExit = QtWidgets.QAction(ThunderNOTBird)
        self.actionExit.setObjectName("actionExit")
        self.actionProject_info = QtWidgets.QAction(ThunderNOTBird)
        self.actionProject_info.setObjectName("actionProject_info")
        self.actionVersion = QtWidgets.QAction(ThunderNOTBird)
        self.actionVersion.setObjectName("actionVersion")
        self.menuFile.addAction(self.actionCreate_a_new_message)
        self.menuFile.addAction(self.actionDelete_message)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionProject_info)
        self.menuAbout.addAction(self.actionVersion)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ThunderNOTBird)
        QtCore.QMetaObject.connectSlotsByName(ThunderNOTBird)

    def retranslateUi(self, ThunderNOTBird):
        _translate = QtCore.QCoreApplication.translate
        ThunderNOTBird.setWindowTitle(_translate("ThunderNOTBird", "MainWindow"))
        __sortingEnabled = self.foldersListWidget.isSortingEnabled()
        self.foldersListWidget.setSortingEnabled(False)
        item = self.foldersListWidget.item(0)
        item.setText(_translate("ThunderNOTBird", "Inbox"))
        item = self.foldersListWidget.item(1)
        item.setText(_translate("ThunderNOTBird", "Sent"))
        item = self.foldersListWidget.item(2)
        item.setText(_translate("ThunderNOTBird", "Trash"))
        self.foldersListWidget.setSortingEnabled(__sortingEnabled)
        item = self.mailTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ThunderNOTBird", "From"))
        item = self.mailTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ThunderNOTBird", "Subject"))
        item = self.mailTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ThunderNOTBird", "Date"))
        self.createMessageToolButton.setText(
            _translate("ThunderNOTBird", "Create a message")
        )
        self.menuFile.setTitle(_translate("ThunderNOTBird", "File"))
        self.menuAbout.setTitle(_translate("ThunderNOTBird", "About"))
        self.actionCreate_a_new_message.setText(
            _translate("ThunderNOTBird", "Create a new message")
        )
        self.actionDelete_message.setText(
            _translate("ThunderNOTBird", "Delete message")
        )
        self.actionExit.setText(_translate("ThunderNOTBird", "Exit"))
        self.actionProject_info.setText(_translate("ThunderNOTBird", "Project info"))
        self.actionVersion.setText(_translate("ThunderNOTBird", "Version"))
